version: '3'
services:
  student_service:
    build: ./student-app
    restart: unless-stopped
    image: tlcandeias/student_service
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "8080:8080"

  mongo:
    restart: unless-stopped
    env_file: ./.env
    image: mongo:4
    ports:
      - $MONGO_HOST_PORT:$MONGO_HOST_PORT
