name: Builb Test and push
on: [push]
env:
  IMAGE_NAME: student_service
  REPO_NAME: tlcandeias

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker-compose
      run: |
        docker-compose up --build -d
    - name: Find the built image ID
      id: docker_image_id
      run: echo "::set-output name=image_id::$(docker images -q student_service)"
    - name: Tag the Docker image
      run: |
        docker tag ${{ steps.docker_image_id.outputs.image_id }} $REPO_NAME/$IMAGE_NAME:latest
    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: postman/collection.json
        environment: postman/environment.json
        reporters: cli
        iterationCount: 3

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}


    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      run: | 
          docker push $REPO_NAME/$IMAGE_NAME
