name: Builb Test and push
on: [push]
env:
  IMAGE_NAME: student_service
  REPO_NAME: tlcandeias

jobs:
  mongodb-service:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run MongoDB
      run: |
        docker run -d --name mongodb -p 27017:27017 mongo:latest
        sleep 10 # Wait for MongoDB to fully start
    - name: Build docker
      run: |
        docker build ./student-app -t $REPO_NAME/$IMAGE_NAME
    - name: run docker
      run: |
        docker run -d -e 8080:8080 -host=172.17.0.2 $REPO_NAME/$IMAGE_NAME:latest && \
          docker ps && sleep 5
    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: postman/collection.json
        environment: postman/environment.json
        reporters: cli
        iterationCount: 3

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}


    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      run: | 
          docker push $REPO_NAME/$IMAGE_NAME
